apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-web
  labels:
    app: flask-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-web
  template:
    metadata:
      labels:
        app: flask-web
    spec:
      containers:
      - name: flask-web
        image: thoang/flask-k8s-demo:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-web
spec:
  selector:
    app: flask-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-web-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: flask.local   # sửa domain theo ý bạn (hoặc dùng IP của master node)
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-web
            port:
              number: 80
